# Generated by Django 2.0.3 on 2018-04-05 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0010_auto_20180405_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='term',
            field=models.CharField(choices=[('SU', 'Summer'), ('FA', 'Fall'), ('SP', 'Spring')], max_length=255),
        ),
    ]
