# Generated by Django 2.0.3 on 2018-04-05 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0011_auto_20180405_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='courses',
            field=models.ManyToManyField(blank=True, to='groups.Course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='term',
            field=models.CharField(choices=[('SUMMER', 'Summer'), ('FALL', 'Fall'), ('SPRING', 'Spring')], max_length=255),
        ),
    ]
