# Generated by Django 2.0.3 on 2018-04-07 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0013_auto_20180406_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='courses',
            field=models.ManyToManyField(blank=True, to='groups.Course'),
        ),
    ]
